cmake_minimum_required(VERSION 3.12)

mapnn_config_map_begin(KernelStage)

mapnn_enable_map(general/kernel/map_pad_avgpool2x2s1.h       ON)
mapnn_enable_map(general/kernel/map_pad_avgpool3x3s1.h       ON)
mapnn_enable_map(general/kernel/map_pad_avgpool3x3s2.h       ON)
mapnn_enable_map(general/kernel/map_pad_avgpool.h            ON)
mapnn_enable_map(general/kernel/map_pad_conv3x3s1_same.h     ON)
mapnn_enable_map(general/kernel/map_pad_conv.h               ON)
mapnn_enable_map(general/kernel/map_pad_deconv.h             ON)
mapnn_enable_map(general/kernel/map_pad_maxpool2x2s1.h       ON)
mapnn_enable_map(general/kernel/map_pad_maxpool3x3s1.h       ON)
mapnn_enable_map(general/kernel/map_pad_maxpool3x3s2.h       ON)
mapnn_enable_map(general/kernel/map_pad_maxpool.h            ON)
mapnn_enable_map(general/kernel/map_ref_add.h                ON)
mapnn_enable_map(general/kernel/map_ref_batchnormal.h        ON)
mapnn_enable_map(general/kernel/map_ref_clip.h               ON)
mapnn_enable_map(general/kernel/map_ref_concat.h             ON)
mapnn_enable_map(general/kernel/map_ref_crop.h               ON)
mapnn_enable_map(general/kernel/map_ref_dropout.h            ON)
mapnn_enable_map(general/kernel/map_ref_div.h                ON)
mapnn_enable_map(general/kernel/map_ref_flatten.h            ON)
mapnn_enable_map(general/kernel/map_ref_gemm.h               ON)
mapnn_enable_map(general/kernel/map_ref_global_avgpool.h     ON)
mapnn_enable_map(general/kernel/map_ref_global_maxpool.h     ON)
mapnn_enable_map(general/kernel/map_ref_leakyrelu.h          ON)
mapnn_enable_map(general/kernel/map_ref_lrn.h                ON)
mapnn_enable_map(general/kernel/map_ref_math.h               ON)
mapnn_enable_map(general/kernel/map_ref_max.h                ON)
mapnn_enable_map(general/kernel/map_ref_min.h                ON)
mapnn_enable_map(general/kernel/map_ref_mvn.h                ON)
mapnn_enable_map(general/kernel/map_ref_mul.h                ON)
mapnn_enable_map(general/kernel/map_ref_nop.h                ON)
mapnn_enable_map(general/kernel/map_ref_pad.h                ON)
mapnn_enable_map(general/kernel/map_ref_pow.h                ON)
mapnn_enable_map(general/kernel/map_ref_power.h              ON)
mapnn_enable_map(general/kernel/map_ref_prelu.h              ON)
mapnn_enable_map(general/kernel/map_ref_relu6.h              ON)
mapnn_enable_map(general/kernel/map_ref_relu.h               ON)
mapnn_enable_map(general/kernel/map_ref_elu.h                ON)
mapnn_enable_map(general/kernel/map_ref_shuffle_channel.h    ON)
mapnn_enable_map(general/kernel/map_ref_reshape.h            ON)
mapnn_enable_map(general/kernel/map_ref_resize.h             ON)
mapnn_enable_map(general/kernel/map_ref_upsample.h           ON)
mapnn_enable_map(general/kernel/map_ref_scale.h              ON)
mapnn_enable_map(general/kernel/map_ref_slice.h              ON)
mapnn_enable_map(general/kernel/map_ref_softmax.h            ON)
mapnn_enable_map(general/kernel/map_ref_transpose.h          ON)
mapnn_enable_map(general/kernel/map_ref_sigmoid.h            ON)

mapnn_config_map_end(kernel_stage.h)
