cmake_minimum_required(VERSION 3.12)

if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64)|(X86_64)|(x64)|(X64)|(amd64)|(AMD64)|(i686)")
    message(STATUS "mapnn build with sse42")
    option(MCNN_BUILD_WITH_SSE42 "" ON)
    add_definitions(-msse4.1)
    add_definitions(-DMCNN_USE_SSE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^armv7" OR ARCHS MATCHES "^armv7(;armv7s)?")
    message(STATUS "mapnn build with neon")
    option(MCNN_BUILD_WITH_NEON "" ON)
    add_definitions(-DMCNN_USE_NEON32)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^aarch64" OR ARCHS STREQUAL "arm64")
    message(STATUS "mapnn build with asimd")
    option(MCNN_BUILD_WITH_ASIMD "" ON)
    add_definitions(-DMCNN_USE_NEON64)
else()
    message(STATUS "mapnn build with none")
endif()
