on: [push, pull_request]
jobs:
  android-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run:  git submodule update --init
    - name: configure
      run:  mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../toolchains/Android-x64.toolchain.cmake
    - name: build
      run:  cmake --build build -j 2
