on: [push, pull_request]
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run:  git submodule update --init
    - name: configure
      run:  mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build -j 2

